OSOE-49: Update member order and remove section about code islands
Lombiq/Orchard-Dojo-Library pull request #9
Opened 2022-05-25 14:55 UTC by DAud-IcI

OSOE-49

2022-05-25 15:15 UTC, 0liver requested changes

2022-05-25 15:15 UTC, 0liver commented on Library/DevelopmentGuidelines/CodeStyling.md
> +Within this order fields and properties are sorted private, protected, public.
```suggestion
Within this order, fields and properties are sorted private, protected, public.
```

2022-05-25 15:15 UTC, 0liver commented on Library/DevelopmentGuidelines/CodeStyling.md
> +- readonly fields
```suggestion
- constant fields
- static fields
- readonly fields
```

2022-05-25 15:15 UTC, 0liver commented on Library/DevelopmentGuidelines/CodeStyling.md
>          private static string _myStaticField = "field";
These two should be swapped.

2022-05-25 15:15 UTC, 0liver commented on Library/DevelopmentGuidelines/CodeStyling.md
>          private static void MyStaticMethod()
Let's add that `public static void MyPublicStaticMethod()` above this one, so we don't have to interpolate. (I read your comment above, but still.)

2022-05-25 15:46 UTC, DAud-IcI commented on Library/DevelopmentGuidelines/CodeStyling.md
> +- readonly fields
That's not right. All readonly fields must come before non-readonly fields or the analyzer will throw a warning.

2022-05-25 15:48 UTC, sarahelsaig commented on Library/DevelopmentGuidelines/CodeStyling.md
>          private static string _myStaticField = "field";
No,  for the reason I wrote above.

2022-05-25 15:55 UTC, DAud-IcI commented on Library/DevelopmentGuidelines/CodeStyling.md
>          private static void MyStaticMethod()
Ok added.

2022-05-25 16:03 UTC, 0liver commented on Library/DevelopmentGuidelines/CodeStyling.md
> +- readonly fields
I don't get any analyzer warning for this:

```c#
public class PrivacyConsentService : IPrivacyConsentService
{
    private const string _const = nameof(PrivacyConsentService);
    private static string _prop = typeof(PrivacyConsentService).FullName;

    private readonly UserManager<IUser> _userManager;
    private readonly IUserService _userService;

    // ...
}
```

2022-05-25 16:06 UTC, 0liver commented on Library/DevelopmentGuidelines/CodeStyling.md
> +- readonly fields
It also makes the most sense to me to have `const`, `static`, and instance members in that order for fields, and in the reverse order for methods. And that's the order I've defined in my file layout, too:

![image](https://user-images.githubusercontent.com/164360/170307435-abb74341-2037-44fe-ab0d-688ccf8ff26a.png)

2022-05-25 18:51 UTC, DAud-IcI commented on Library/DevelopmentGuidelines/CodeStyling.md
> +- readonly fields
This is what you get in OSOCE if you flip the two fields as you suggested.
![image](https://user-images.githubusercontent.com/4007293/170346170-7590528e-6159-48b3-b1bc-bc4f4424433c.png)

2022-05-25 18:52 UTC, DAud-IcI commented on Library/DevelopmentGuidelines/CodeStyling.md
> +- readonly fields
See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1214.md

2022-05-25 20:05 UTC, 0liver commented on Library/DevelopmentGuidelines/CodeStyling.md
> +- readonly fields
OK, we have quite a few dimensions to map onto a single one (order) here:

- `const`, `static`, or `instance`
- `public`, `protected`, `private`
- `readonly`, not readonly

Let's follow the analyzer then.

Tbh, I haven't encountered any situation in the last year where a static field would be non-readonly.

2022-05-26 12:08 UTC, 0liver requested changes

2022-05-26 12:08 UTC, 0liver commented on Library/DevelopmentGuidelines/CodeStyling.md
> +Within this order, fields and properties are sorted private, protected, public.
```suggestion
Within this order, fields and properties are sorted first by static vs. non-static, and inside each of these by private, protected, public.

```

2022-05-26 12:08 UTC, 0liver commented
This one slipped through, but let's finish it.

2022-05-26 12:10 UTC, DAud-IcI commented on Library/DevelopmentGuidelines/CodeStyling.md
> +Within this order, fields and properties are sorted private, protected, public.
ok

2022-05-26 12:26 UTC, 0liver approved these changes

2022-05-26 12:26 UTC, merged